language: ruby
rvm:
  - 2.1.3
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - jruby
  - ruby-head
  - rbx-2
matrix:
  allow_failures:
    - rvm: jruby
    - rvm: ruby-head
    - rvm: rbx-2
  fast_finish: true

gemfile:
  - gemfiles/rails_3.gemfile
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_4.1.gemfile
